// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACFBkNhuluy0WgzJVCxi2yN8xPTkdr1bk',
    appId: '1:134047785603:web:bd3544df984dfe6d7cb1b6',
    messagingSenderId: '134047785603',
    projectId: 'to-do-list-dc4d7',
    authDomain: 'to-do-list-dc4d7.firebaseapp.com',
    storageBucket: 'to-do-list-dc4d7.appspot.com',
    measurementId: 'G-TENJX3K3EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEkhHOQxX1j6bN8BgUw1x5IMKgPet8xAM',
    appId: '1:134047785603:android:c1f417db0686d8107cb1b6',
    messagingSenderId: '134047785603',
    projectId: 'to-do-list-dc4d7',
    storageBucket: 'to-do-list-dc4d7.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU8QZepgAfihg_4NMgnFwcWc-HGPFPU0Y',
    appId: '1:134047785603:ios:bedb8d70a77653b77cb1b6',
    messagingSenderId: '134047785603',
    projectId: 'to-do-list-dc4d7',
    storageBucket: 'to-do-list-dc4d7.appspot.com',
    iosBundleId: 'com.example.flutterTodolistfirebase.RunnerTests',
  );
}
