// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzW0RzFZznoeiwjN7qL0FReN7wpwTiMRA',
    appId: '1:698150285195:web:5934148eab736ec859498e',
    messagingSenderId: '698150285195',
    projectId: 'todo-application-d2cb6',
    authDomain: 'todo-application-d2cb6.firebaseapp.com',
    storageBucket: 'todo-application-d2cb6.firebasestorage.app',
    measurementId: 'G-1K9BE1K9Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSL23N05UCejYlj79tPfX_og9LcoJ5CV4',
    appId: '1:698150285195:android:43bd7e22378709fa59498e',
    messagingSenderId: '698150285195',
    projectId: 'todo-application-d2cb6',
    storageBucket: 'todo-application-d2cb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6FCOLYGpCKIPwCqH7Dk7U0qPi0RXa27o',
    appId: '1:698150285195:ios:27ca04d671f1397359498e',
    messagingSenderId: '698150285195',
    projectId: 'todo-application-d2cb6',
    storageBucket: 'todo-application-d2cb6.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodolistfirebase',
  );
}
